#!/bin/bash
#
# script:   sshfp
# author:   Aaron Russo <arusso@berkeley.edu>
# purpose:  Prints out the servers SSHFP keys
# date:     23-March-2012
# notes:    Tested on OSX 10.7 and RHEL6
###################################################################

# Error Codes
ERR_BAD_DIR=1  # invalid directory passed
ERR_UNKNOWN=2  # unknown platform type

# Variables
UNAME=`uname`
PLATFORM='Unknown'

if [[ $# -gt 0 ]]; then # we got an arg, lets see if its a valid directory
    if [[ -d "$1" ]]; then # we got a good dir, lets use it
	HOST_SSH_DIR="$1"
    else
	echo "Passed a non-existant directory ${1}"
	exit ERR_BAD_DIR
    fi  
elif [[ "$UNAME" == "Linux" ]]; then
    PLATFORM='linux'
    HOST_SSH_DIR='/etc/ssh/'
elif [[ "$UNAME" == "Darwin" ]]; then
    PLATFORM='osx'
    HOST_SSH_DIR='/etc/'
else
    echo "Unable to continue, unknown platform '${UNAME}' detected"
    exit ERR_UNKNOWN
fi

if [[ -r "${HOST_SSH_DIR}/ssh_host_rsa_key.pub" ]]; then # we can read the file
    
    SSHFP1=`cat ${HOST_SSH_DIR}ssh_host_rsa_key.pub | cut -d ' ' -f 2 | openssl base64 -d -A | openssl sha1`
    echo "`hostname` IN SSHFP 1 1 ${SSHFP1}"
else
    echo "Error: Unable to locate the SSHFP 1 1 (RSA) key."
fi

if [[ -r "${HOST_SSH_DIR}/ssh_host_dsa_key.pub" ]]; then # we can read the file
    SSHFP2=`cat ${HOST_SSH_DIR}ssh_host_dsa_key.pub | cut -d ' ' -f 2 | openssl base64 -d -A | openssl sha1`
    echo "`hostname` IN SSHFP 2 1 ${SSHFP2}"
else
    echo "Error: Unable to locate the SSHFP 2 1 (DSA) key."
fi